### ISSUE TITLE
Assertion error when using snippetx

### ISSUE THREAD

**Issue by natet** [ColinRyan/SnippetX#2]
I'm getting the following error when I hit alt+x to apply a snippet on a single line of csv data:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 798, in run_
    return self.run(edit)
  File "snippetx in /Users/natet/Library/Application Support/Sublime Text 3/Installed Packages/SnippetX.sublime-package", line 142, in run
  File "snippetx in /Users/natet/Library/Application Support/Sublime Text 3/Installed Packages/SnippetX.sublime-package", line 88, in getData
AssertionError

If I copy the regular expression used in snippetx and attempt to use it in a find dialog, I get an error "Ran out of stack space trying to match the regular expression.

I'm using sublimetext 3 build 3118 on a Mac

**Comment by ColinRyan** [comment]
hey, thanks for the info and apologies for the late reply.  I'm going to fix this asap.

**Comment by ColinRyan** [comment]
Can you get me the line of csv and the snippet you were using?

**Comment by ntenney** [comment]
`12345,'John','Doe','Mike','555-555-5555','john.doe@nospam.org'`

The snippet is a custom snippet:

`<snippet>
    <content><![CDATA[
update g_job_final_resolved set FIRST_NAME=$2, LAST_NAME=$3, MIDDLE_NAME=$4, PHONE=$5, EMAIL_ADDR=$6 where id_user='$1';
]]></content>
    
    <tabTrigger>mscfdata</tabTrigger>
    
    
    <scope>source.sql</scope>
</snippet>`

**Comment by ntenney** [comment]
I think the issue has something to do with the block of text above where I'm attempting to do the snippet replacement. In my file, I have 70 lines of sql statements in a solid block. If I put blank lines at various points in the file, then the replacement works. With the above sample data, if I take the line generated by the snippet and clone it 21 times then attempt to run the snippetx block, I get the error. I'm guessing it has something to do with the number of characters in the block being matched by the regex.

**Comment by ntenney** [comment]
Sorry, I'm natet. That's my other account.
